#!/bin/bash # QoL: So this file is consistently detectable as shell script.
# This script is meant to be source interpreted (and it has a-x permissions) so it makes no difference.

# Source version: v1.0.0-beta

ngx_module_type=HTTP
ngx_module_name=ngx_http_jwt_module
ngx_module_incs="$ngx_addon_dir"
ngx_module_deps=
ngx_module_srcs="$ngx_addon_dir/ngx_http_jwt.c \
                  $ngx_addon_dir/ngx_http_jwt_jwks_storage.c \
                  $ngx_addon_dir/ngx_http_jwt_request_transaction.c \
                  $ngx_addon_dir/ngx_http_jwt_memory.c"
ngx_module_libs="-ljansson -ljwt"

# Default ngx_module_order should work.

. auto/module

ngx_addon_name=$ngx_module_name
